name: バグ報告
description: バグを報告する
title: "バグ："
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: バグの説明
      description: バグの内容を明確かつ簡潔に記述してください。
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: 再現手順
      description: バグを再現する手順を記述してください。
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: 期待される動作
      description: 本来どのように動作すべきかを記述してください。
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: スクリーンショット
      description: 該当する場合は、スクリーンショットを追加してください。
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: 環境
      description: バグが発生した環境を選択してください。（複数選択可）
      multiple: true
      options:
        - Chrome
        - Chrome(スマホ)
        - Firefox
        - Microsoft Edge
        - Safari
    validations:
      required: true