name: 機能要望
description: 新機能や改善を提案する
title: "機能要望："
labels: ["enhancement"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: 機能の説明
      description: 追加してほしい機能や改善点を記述してください。
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: 解決したい課題
      description: この機能がどのような問題を解決するか記述してください。
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: 代替案
      description: 検討した代替案があれば記述してください。
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: 補足情報
      description: スクリーンショットや参考リンクなど、補足情報があれば追加してください。
    validations:
      required: false
